language: go

go:
  - 1.16.x

before_install:
  - go mod download

script:
  - go test -cpu=1,2 -v -tags integration ./...

deploy:
  provider: gae
  keyfile: "client-secret.json"
  project: "modanisa.challenge"
  on: main
