apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mesutuzun/ch_backend_backend:latest
        ports:
        - containerPort: 10000
        
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
    - port: 10000
      targetPort: 10000
  selector:
    name: backend-service

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: backend-service
            port:
              number: 10000
        path: /
        pathType: Prefix